package com.valvesoftware.android.steam.community;

/* renamed from: com.valvesoftware.android.steam.community.R */
public final class C0151R {

    /* renamed from: com.valvesoftware.android.steam.community.R.styleable */
    public static final class styleable {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 24;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 26;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 25;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] CompatTextView;
        public static final int CompatTextView_textAllCaps = 0;
        public static final int[] DrawerArrowToggle;
        public static final int DrawerArrowToggle_barSize = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_middleBarArrowSize = 5;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int DrawerArrowToggle_topBottomBarArrowSize = 4;
        public static final int[] LinearLayoutCompat;
        public static final int[] LinearLayoutCompat_Layout;
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int[] ListPopupWindow;
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int[] MapAttrs;
        public static final int MapAttrs_cameraBearing = 1;
        public static final int MapAttrs_cameraTargetLat = 2;
        public static final int MapAttrs_cameraTargetLng = 3;
        public static final int MapAttrs_cameraTilt = 4;
        public static final int MapAttrs_cameraZoom = 5;
        public static final int MapAttrs_mapType = 0;
        public static final int MapAttrs_uiCompass = 6;
        public static final int MapAttrs_uiRotateGestures = 7;
        public static final int MapAttrs_uiScrollGestures = 8;
        public static final int MapAttrs_uiTiltGestures = 9;
        public static final int MapAttrs_uiZoomControls = 10;
        public static final int MapAttrs_uiZoomGestures = 11;
        public static final int MapAttrs_useViewLifecycle = 12;
        public static final int MapAttrs_zOrderOnTop = 13;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int[] PopupWindow;
        public static final int[] PopupWindowBackgroundState;
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 1;
        public static final int[] SearchView;
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 7;
        public static final int SearchView_commitIcon = 11;
        public static final int SearchView_goIcon = 8;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 13;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchIcon = 9;
        public static final int SearchView_submitBackground = 14;
        public static final int SearchView_suggestionRowLayout = 12;
        public static final int SearchView_voiceIcon = 10;
        public static final int[] Spinner;
        public static final int Spinner_android_background = 1;
        public static final int Spinner_android_dropDownHorizontalOffset = 5;
        public static final int Spinner_android_dropDownSelector = 2;
        public static final int Spinner_android_dropDownVerticalOffset = 6;
        public static final int Spinner_android_dropDownWidth = 4;
        public static final int Spinner_android_gravity = 0;
        public static final int Spinner_android_popupBackground = 3;
        public static final int Spinner_disableChildrenWhenDisabled = 10;
        public static final int Spinner_popupPromptView = 9;
        public static final int Spinner_prompt = 7;
        public static final int Spinner_spinnerMode = 8;
        public static final int[] SteamWebButton;
        public static final int SteamWebButton_bottomBorder = 3;
        public static final int SteamWebButton_detailText = 1;
        public static final int SteamWebButton_titleText = 0;
        public static final int SteamWebButton_topBorder = 2;
        public static final int[] SwitchCompat;
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 9;
        public static final int SwitchCompat_splitTrack = 8;
        public static final int SwitchCompat_switchMinWidth = 6;
        public static final int SwitchCompat_switchPadding = 7;
        public static final int SwitchCompat_switchTextAppearance = 5;
        public static final int SwitchCompat_thumbTextPadding = 4;
        public static final int SwitchCompat_track = 3;
        public static final int[] Theme;
        public static final int Theme_actionBarDivider = 19;
        public static final int Theme_actionBarItemBackground = 20;
        public static final int Theme_actionBarPopupTheme = 13;
        public static final int Theme_actionBarSize = 18;
        public static final int Theme_actionBarSplitStyle = 15;
        public static final int Theme_actionBarStyle = 14;
        public static final int Theme_actionBarTabBarStyle = 9;
        public static final int Theme_actionBarTabStyle = 8;
        public static final int Theme_actionBarTabTextStyle = 10;
        public static final int Theme_actionBarTheme = 16;
        public static final int Theme_actionBarWidgetTheme = 17;
        public static final int Theme_actionButtonStyle = 43;
        public static final int Theme_actionDropDownStyle = 38;
        public static final int Theme_actionMenuTextAppearance = 21;
        public static final int Theme_actionMenuTextColor = 22;
        public static final int Theme_actionModeBackground = 25;
        public static final int Theme_actionModeCloseButtonStyle = 24;
        public static final int Theme_actionModeCloseDrawable = 27;
        public static final int Theme_actionModeCopyDrawable = 29;
        public static final int Theme_actionModeCutDrawable = 28;
        public static final int Theme_actionModeFindDrawable = 33;
        public static final int Theme_actionModePasteDrawable = 30;
        public static final int Theme_actionModePopupWindowStyle = 35;
        public static final int Theme_actionModeSelectAllDrawable = 31;
        public static final int Theme_actionModeShareDrawable = 32;
        public static final int Theme_actionModeSplitBackground = 26;
        public static final int Theme_actionModeStyle = 23;
        public static final int Theme_actionModeWebSearchDrawable = 34;
        public static final int Theme_actionOverflowButtonStyle = 11;
        public static final int Theme_actionOverflowMenuStyle = 12;
        public static final int Theme_activityChooserViewStyle = 50;
        public static final int Theme_android_windowIsFloating = 0;
        public static final int Theme_buttonBarButtonStyle = 45;
        public static final int Theme_buttonBarStyle = 44;
        public static final int Theme_colorAccent = 77;
        public static final int Theme_colorButtonNormal = 81;
        public static final int Theme_colorControlActivated = 79;
        public static final int Theme_colorControlHighlight = 80;
        public static final int Theme_colorControlNormal = 78;
        public static final int Theme_colorPrimary = 75;
        public static final int Theme_colorPrimaryDark = 76;
        public static final int Theme_colorSwitchThumbNormal = 82;
        public static final int Theme_dividerHorizontal = 49;
        public static final int Theme_dividerVertical = 48;
        public static final int Theme_dropDownListViewStyle = 67;
        public static final int Theme_dropdownListPreferredItemHeight = 39;
        public static final int Theme_editTextBackground = 56;
        public static final int Theme_editTextColor = 55;
        public static final int Theme_homeAsUpIndicator = 42;
        public static final int Theme_listChoiceBackgroundIndicator = 74;
        public static final int Theme_listPopupWindowStyle = 68;
        public static final int Theme_listPreferredItemHeight = 62;
        public static final int Theme_listPreferredItemHeightLarge = 64;
        public static final int Theme_listPreferredItemHeightSmall = 63;
        public static final int Theme_listPreferredItemPaddingLeft = 65;
        public static final int Theme_listPreferredItemPaddingRight = 66;
        public static final int Theme_panelBackground = 71;
        public static final int Theme_panelMenuListTheme = 73;
        public static final int Theme_panelMenuListWidth = 72;
        public static final int Theme_popupMenuStyle = 53;
        public static final int Theme_popupWindowStyle = 54;
        public static final int Theme_searchViewStyle = 61;
        public static final int Theme_selectableItemBackground = 46;
        public static final int Theme_selectableItemBackgroundBorderless = 47;
        public static final int Theme_spinnerDropDownItemStyle = 41;
        public static final int Theme_spinnerStyle = 40;
        public static final int Theme_switchStyle = 57;
        public static final int Theme_textAppearanceLargePopupMenu = 36;
        public static final int Theme_textAppearanceListItem = 69;
        public static final int Theme_textAppearanceListItemSmall = 70;
        public static final int Theme_textAppearanceSearchResultSubtitle = 59;
        public static final int Theme_textAppearanceSearchResultTitle = 58;
        public static final int Theme_textAppearanceSmallPopupMenu = 37;
        public static final int Theme_textColorSearchUrl = 60;
        public static final int Theme_toolbarNavigationButtonStyle = 52;
        public static final int Theme_toolbarStyle = 51;
        public static final int Theme_windowActionBar = 1;
        public static final int Theme_windowActionBarOverlay = 2;
        public static final int Theme_windowActionModeOverlay = 3;
        public static final int Theme_windowFixedHeightMajor = 7;
        public static final int Theme_windowFixedHeightMinor = 5;
        public static final int Theme_windowFixedWidthMajor = 4;
        public static final int Theme_windowFixedWidthMinor = 6;
        public static final int[] Toolbar;
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_collapseContentDescription = 19;
        public static final int Toolbar_collapseIcon = 18;
        public static final int Toolbar_contentInsetEnd = 5;
        public static final int Toolbar_contentInsetLeft = 6;
        public static final int Toolbar_contentInsetRight = 7;
        public static final int Toolbar_contentInsetStart = 4;
        public static final int Toolbar_maxButtonHeight = 16;
        public static final int Toolbar_navigationContentDescription = 21;
        public static final int Toolbar_navigationIcon = 20;
        public static final int Toolbar_popupTheme = 8;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 10;
        public static final int Toolbar_theme = 17;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMarginBottom = 15;
        public static final int Toolbar_titleMarginEnd = 13;
        public static final int Toolbar_titleMarginStart = 12;
        public static final int Toolbar_titleMarginTop = 14;
        public static final int Toolbar_titleMargins = 11;
        public static final int Toolbar_titleTextAppearance = 9;
        public static final int[] TwoFactorCodeListFragment;
        public static final int TwoFactorCodeListFragment_invisibleIfNoCodes = 0;
        public static final int[] TypefaceTextView;
        public static final int TypefaceTextView_typeface = 0;
        public static final int[] View;
        public static final int[] ViewStubCompat;
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 0;
        public static final int View_paddingEnd = 2;
        public static final int View_paddingStart = 1;

        static {
            ActionBar = new int[]{C0151R.attr.height, C0151R.attr.title, C0151R.attr.navigationMode, C0151R.attr.displayOptions, C0151R.attr.subtitle, C0151R.attr.titleTextStyle, C0151R.attr.subtitleTextStyle, C0151R.attr.icon, C0151R.attr.logo, C0151R.attr.divider, C0151R.attr.background, C0151R.attr.backgroundStacked, C0151R.attr.backgroundSplit, C0151R.attr.customNavigationLayout, C0151R.attr.homeLayout, C0151R.attr.progressBarStyle, C0151R.attr.indeterminateProgressStyle, C0151R.attr.progressBarPadding, C0151R.attr.itemPadding, C0151R.attr.hideOnContentScroll, C0151R.attr.contentInsetStart, C0151R.attr.contentInsetEnd, C0151R.attr.contentInsetLeft, C0151R.attr.contentInsetRight, C0151R.attr.elevation, C0151R.attr.popupTheme, C0151R.attr.homeAsUpIndicator};
            int[] iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = 16842931;
            ActionBarLayout = iArr;
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[View_android_focusable];
            ActionMode = new int[]{C0151R.attr.height, C0151R.attr.titleTextStyle, C0151R.attr.subtitleTextStyle, C0151R.attr.background, C0151R.attr.backgroundSplit, C0151R.attr.closeItemLayout};
            ActivityChooserView = new int[]{C0151R.attr.initialActivityCount, C0151R.attr.expandActivityOverflowButtonDrawable};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0151R.attr.textAllCaps;
            CompatTextView = iArr;
            DrawerArrowToggle = new int[]{C0151R.attr.color, C0151R.attr.spinBars, C0151R.attr.drawableSize, C0151R.attr.gapBetweenBars, C0151R.attr.topBottomBarArrowSize, C0151R.attr.middleBarArrowSize, C0151R.attr.barSize, C0151R.attr.thickness};
            LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, C0151R.attr.divider, C0151R.attr.measureWithLargestChild, C0151R.attr.showDividers, C0151R.attr.dividerPadding};
            LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
            ListPopupWindow = new int[]{16843436, 16843437};
            MapAttrs = new int[]{C0151R.attr.mapType, C0151R.attr.cameraBearing, C0151R.attr.cameraTargetLat, C0151R.attr.cameraTargetLng, C0151R.attr.cameraTilt, C0151R.attr.cameraZoom, C0151R.attr.uiCompass, C0151R.attr.uiRotateGestures, C0151R.attr.uiScrollGestures, C0151R.attr.uiTiltGestures, C0151R.attr.uiZoomControls, C0151R.attr.uiZoomGestures, C0151R.attr.useViewLifecycle, C0151R.attr.zOrderOnTop};
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, C0151R.attr.showAsAction, C0151R.attr.actionLayout, C0151R.attr.actionViewClass, C0151R.attr.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, C0151R.attr.preserveIconSpacing};
            PopupWindow = new int[]{16843126, C0151R.attr.overlapAnchor};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0151R.attr.state_above_anchor;
            PopupWindowBackgroundState = iArr;
            SearchView = new int[]{16842970, 16843039, 16843296, 16843364, C0151R.attr.layout, C0151R.attr.iconifiedByDefault, C0151R.attr.queryHint, C0151R.attr.closeIcon, C0151R.attr.goIcon, C0151R.attr.searchIcon, C0151R.attr.voiceIcon, C0151R.attr.commitIcon, C0151R.attr.suggestionRowLayout, C0151R.attr.queryBackground, C0151R.attr.submitBackground};
            Spinner = new int[]{16842927, 16842964, 16843125, 16843126, 16843362, 16843436, 16843437, C0151R.attr.prompt, C0151R.attr.spinnerMode, C0151R.attr.popupPromptView, C0151R.attr.disableChildrenWhenDisabled};
            SteamWebButton = new int[]{C0151R.attr.titleText, C0151R.attr.detailText, C0151R.attr.topBorder, C0151R.attr.bottomBorder};
            SwitchCompat = new int[]{16843044, 16843045, 16843074, C0151R.attr.track, C0151R.attr.thumbTextPadding, C0151R.attr.switchTextAppearance, C0151R.attr.switchMinWidth, C0151R.attr.switchPadding, C0151R.attr.splitTrack, C0151R.attr.showText};
            Theme = new int[]{16842839, C0151R.attr.windowActionBar, C0151R.attr.windowActionBarOverlay, C0151R.attr.windowActionModeOverlay, C0151R.attr.windowFixedWidthMajor, C0151R.attr.windowFixedHeightMinor, C0151R.attr.windowFixedWidthMinor, C0151R.attr.windowFixedHeightMajor, C0151R.attr.actionBarTabStyle, C0151R.attr.actionBarTabBarStyle, C0151R.attr.actionBarTabTextStyle, C0151R.attr.actionOverflowButtonStyle, C0151R.attr.actionOverflowMenuStyle, C0151R.attr.actionBarPopupTheme, C0151R.attr.actionBarStyle, C0151R.attr.actionBarSplitStyle, C0151R.attr.actionBarTheme, C0151R.attr.actionBarWidgetTheme, C0151R.attr.actionBarSize, C0151R.attr.actionBarDivider, C0151R.attr.actionBarItemBackground, C0151R.attr.actionMenuTextAppearance, C0151R.attr.actionMenuTextColor, C0151R.attr.actionModeStyle, C0151R.attr.actionModeCloseButtonStyle, C0151R.attr.actionModeBackground, C0151R.attr.actionModeSplitBackground, C0151R.attr.actionModeCloseDrawable, C0151R.attr.actionModeCutDrawable, C0151R.attr.actionModeCopyDrawable, C0151R.attr.actionModePasteDrawable, C0151R.attr.actionModeSelectAllDrawable, C0151R.attr.actionModeShareDrawable, C0151R.attr.actionModeFindDrawable, C0151R.attr.actionModeWebSearchDrawable, C0151R.attr.actionModePopupWindowStyle, C0151R.attr.textAppearanceLargePopupMenu, C0151R.attr.textAppearanceSmallPopupMenu, C0151R.attr.actionDropDownStyle, C0151R.attr.dropdownListPreferredItemHeight, C0151R.attr.spinnerStyle, C0151R.attr.spinnerDropDownItemStyle, C0151R.attr.homeAsUpIndicator, C0151R.attr.actionButtonStyle, C0151R.attr.buttonBarStyle, C0151R.attr.buttonBarButtonStyle, C0151R.attr.selectableItemBackground, C0151R.attr.selectableItemBackgroundBorderless, C0151R.attr.dividerVertical, C0151R.attr.dividerHorizontal, C0151R.attr.activityChooserViewStyle, C0151R.attr.toolbarStyle, C0151R.attr.toolbarNavigationButtonStyle, C0151R.attr.popupMenuStyle, C0151R.attr.popupWindowStyle, C0151R.attr.editTextColor, C0151R.attr.editTextBackground, C0151R.attr.switchStyle, C0151R.attr.textAppearanceSearchResultTitle, C0151R.attr.textAppearanceSearchResultSubtitle, C0151R.attr.textColorSearchUrl, C0151R.attr.searchViewStyle, C0151R.attr.listPreferredItemHeight, C0151R.attr.listPreferredItemHeightSmall, C0151R.attr.listPreferredItemHeightLarge, C0151R.attr.listPreferredItemPaddingLeft, C0151R.attr.listPreferredItemPaddingRight, C0151R.attr.dropDownListViewStyle, C0151R.attr.listPopupWindowStyle, C0151R.attr.textAppearanceListItem, C0151R.attr.textAppearanceListItemSmall, C0151R.attr.panelBackground, C0151R.attr.panelMenuListWidth, C0151R.attr.panelMenuListTheme, C0151R.attr.listChoiceBackgroundIndicator, C0151R.attr.colorPrimary, C0151R.attr.colorPrimaryDark, C0151R.attr.colorAccent, C0151R.attr.colorControlNormal, C0151R.attr.colorControlActivated, C0151R.attr.colorControlHighlight, C0151R.attr.colorButtonNormal, C0151R.attr.colorSwitchThumbNormal};
            Toolbar = new int[]{16842927, 16843072, C0151R.attr.title, C0151R.attr.subtitle, C0151R.attr.contentInsetStart, C0151R.attr.contentInsetEnd, C0151R.attr.contentInsetLeft, C0151R.attr.contentInsetRight, C0151R.attr.popupTheme, C0151R.attr.titleTextAppearance, C0151R.attr.subtitleTextAppearance, C0151R.attr.titleMargins, C0151R.attr.titleMarginStart, C0151R.attr.titleMarginEnd, C0151R.attr.titleMarginTop, C0151R.attr.titleMarginBottom, C0151R.attr.maxButtonHeight, C0151R.attr.theme, C0151R.attr.collapseIcon, C0151R.attr.collapseContentDescription, C0151R.attr.navigationIcon, C0151R.attr.navigationContentDescription};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0151R.attr.invisibleIfNoCodes;
            TwoFactorCodeListFragment = iArr;
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0151R.attr.typeface;
            TypefaceTextView = iArr;
            View = new int[]{16842970, C0151R.attr.paddingStart, C0151R.attr.paddingEnd};
            ViewStubCompat = new int[]{16842960, 16842994, 16842995};
        }
    }
}
